### ISSUE TITLE
downstream analysis

### ISSUE THREAD

**Issue by wangjiawen2013** [brianhie/scanorama#10]
Dear,
Are there any special requirements for the input data (raw counts, cpm, tpm, rpkm or log transformation)? Is the scanorama-corrected data compatible with routine downstream analysis, such as hierarchical clustering, differential expression, duffusion map, pseudotime inference et al ?

**Comment by brianhie** [comment]
The expression values can either be relative expression values (e.g., RPKM or TPM) or absolute transcript counts (e.g., DGE from UMI experiments). The batch corrected data is compatible with downstream analyses (we've used it for diff. expr. and pseudotime inference), but it should work for other analyses as well.
