### ISSUE TITLE
batch correction order

### ISSUE THREAD

**Issue by wangjiawen2013** [brianhie/scanorama#11]
Dear,
Thanks for your great work, it's always a trouble to integrate different datasets.

I have read scanorama supplemental materials in details. It is known that MNN and CCA  are sensitive to the order in which the data sets are considered. According to the scanorama paper, pairs of data sets 𝐷𝑖 and 𝐷𝑗 are in decreasing order of the 𝑟𝑖𝑗 overlap percentages. The first 𝐷𝑖 and 𝐷𝑗 are merged together to initialize a panorama and successive pairs are considered. It seems that the order is depend on the algorithm itself and would not be changed by the users. So, the first Di and Dj (I am not sure Di or Dj) is chosen as the first reference data set and it's expression value would be the same as its raw value. Am I right ? In summary, I wonder that which data set is chosen as the reference data.

Besides, is the colorbar in tsne plot made by raw expression value or corrected expression value ? what's the function of assemble(datasets), I cannot find any tutorials to explain how to use correct(datasets) and aseemble(datasets). it seems that correct() is enough for users, given the corrected data sets, there are a lot of tools to perform the downstream analysis. Perhaps you can provide a detailed document.
Best regards

**Comment by brianhie** [comment]
@wangjiawen2013 The choice of integrating in decreasing order of the rij alignment scores is a bit arbitrary. In Scanorama, there isn't a notion of a "reference" data set.  If there are three data sets A, B, and C, and they all have matches between them, then the algorithm will make corrections based on all matches (i.e., A <=> B, B <=> C, and A <=> C, heuristically ordered based on alignment scores). None of the data sets are guaranteed to have the same raw value before and after batch correction. For example, you could imagine the case in which A's values are corrected to match B's, B's values are corrected to match C's, and C's values are corrected to match A's corrected values.

The expression color bars use values scaled to be within 0 and 1, where 0 is 0 expression and 1 is max expression.

I'll add some documentation to the README with an overview of Scanorama's API.

**Comment by brianhie** [comment]
@wangjiawen2013 Take a look at [the README](README.md) and the top of [`scanorama/scanorama.py`](scanorama/scanorama.py) for some additional API documentation.

**Comment by wangjiawen2013** [comment]
In the example (i.e., A <=> B, B <=> C, and A <=> C, heuristically ordered based on alignment scores), this batch correction is as follows:
(1) A's values are corrected to match B's
(2) B's values are corrected to match C's
(3) C's values are corrected to match A's corrected values
question one:
In step(1), A's values have been corrected to match B's and thus the batch effect is diminished. However, In step(2), B's values are corrected to match C's further, so A's value maybe differ a lot from these corrected B values, that is, the batch effect between A and B would be increased because B's values are corrected to match C's. Similar situation will happen in the successive steps as the same reason. Can I understand the correction process like this ?

question two:
In step(1), what's the rule in deciding whether A's values are corrected to match B's or B's values are corrected to match A's ? If B's values are corrected to match A's, they step(2) will be C's values are corrected to match B's, and step(3) will be A's values are corrected to match C's corrected values. If so, the correction values will be different from that correction process you give in the example.

Besides, could Scanorama be used to align only two datasets ? In this case, is it MNN in essence ?

**Comment by brianhie** [comment]
@wangjiawen2013 Great questions!

To answer question one, in the case of merging A <=> B, B <=> C, and A <=> C (in that order), A and B will be merged into a panorama AB. Then, C will be corrected based on AB's value (a single data set not in a panorama will always be merged into a panorama containing more than one data set, i.e., AB <=> C).  Finally, using the matches in A <=> C, the algorithm will actually align the panorama ABC to itself (i.e., ABC <=> ABC). This keeps an entire panorama together throughout the whole correction process and avoids the problem where a single data set might jump between different batches if it has multiple alignments. This is what all of the logic in https://github.com/brianhie/scanorama/blob/master/scanorama/scanorama.py#L613 is trying to do.

Given just two data sets A and B, the algorithm will use the larger data set as the reference and the smaller data set (in terms of number of cells) as the one to be corrected. And yup, in the case of two data sets the problem reduces to previous MNN implementation; the benefit really comes when integrating many data sets together.
