### ISSUE TITLE
Logic error in `correct` function

### ISSUE THREAD

**Issue by ivirshup** [brianhie/scanorama#13]
Hey,

I think there's a logic error in the current implementation of `correct`. The default value for `hvg` is `None`, which [gets passed](https://github.com/brianhie/scanorama/blob/e4f2c6802ff3ece14faceea53a5d650a71123510/scanorama/scanorama.py#L87) to `process_data`, which tries [`hvg > 0`](https://github.com/brianhie/scanorama/blob/e4f2c6802ff3ece14faceea53a5d650a71123510/scanorama/scanorama.py#L243), which throws (on Python 3.6):

```python
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

I'm really liking the updates to the api and the documentation by the way!

**Comment by brianhie** [comment]
Oops! Fixed in https://github.com/brianhie/scanorama/pull/14
