### ISSUE TITLE
scanorama bbknn and scanpy

### ISSUE THREAD

**Issue by wangjiawen2013** [brianhie/scanorama#15]
Please have a look at this link
https://github.com/Teichlab/bbknn/issues/3#issuecomment-427759950

After getting scanorama_corrected datasets, does it need to do normalization, logarithmize and scale transformation?

**Comment by brianhie** [comment]
@wangjiawen2013 You should do the normalization/preprocessing before inputting to Scanorama. Scanorama correction should come late (or even last) in the data processing pipeline.

**Comment by grst** [comment]
> Scanorama correction should come late (or even last) in the data processing pipeline.

This is important to know! Would you mind adding it to the docs/README so that it's easier to find?

**Comment by brianhie** [comment]
@grst There's a more precise statement on the second line of the README saying:

> Scanorama is designed to be used in scRNA-seq pipelines downstream of noise-reduction methods, including those for normalization, imputation, and highly-variable gene filtering. The results from Scanorama integration and batch correction can then be used as input to other tools for scRNA-seq clustering, visualization, and analysis.

Apologies if it wasn't clear.  I just bolded it to try and make it more apparent.

**Comment by grst** [comment]
RTFD, damn^^

Thanks for highlighting it!
