### ISSUE TITLE
The tutorial address has changed

### ISSUE THREAD

**Issue by zczali4403** [brianhie/scanorama#158]
The address of the tutorial of a simple exercise for integrating three PBMC scRNA-seq datasets (by Åsa Björklund and Paulo Czarnewski) has changed to: https://nbisweden.github.io/workshop-scRNAseq/labs/scanpy/scanpy_03_integration.html. 
So it's better for you to update the README file.

**Comment by brianhie** [comment]
Thanks for the heads up!
