### ISSUE TITLE
Example for 293t_jurkat does not work

### ISSUE THREAD

**Issue by robertamezquita** [brianhie/scanorama#19]
Very small issue; the data needs to be loaded with `load_mtx` rather than `load_data` as called within the `load_names` function in `process.py`. A simple fix, but not sure if this would break any other examples currently in your code.

**Comment by brianhie** [comment]
@robertamezquita thanks for the heads up! The code as is seems to be working for me, can you try to give instructions for replicating and what a fix would be?

**Comment by robertamezquita** [comment]
To replicate, all I ran was what was in the README, `python3 bin/293t_jurkat.py, and it wouldn't work. It returns an error that regarding `load_data` can't find the file names and immediately invokes the `exit(1)` line within that condition. 

The only thing I changed was the call within the `process.py` file was the call of `load_data` to `load_mtx`, and then reran the script with `python3 bin/293t_jurkat.py`again.

**Comment by robertamezquita** [comment]
Probably a separate issue, but here's the latest result of running it with the modified code that allows it to run on my machine:

```
Loaded data/293t_jurkat/293t with 32738 genes and 2885 cells
Loaded data/293t_jurkat/jurkat with 32738 genes and 3258 cells
Loaded data/293t_jurkat/jurkat_293t_50_50 with 32738 genes and 3388 cells
Found 9531 cells among all datasets
After data/293t_jurkat/293t: 32643 genes
After data/293t_jurkat/jurkat: 32643 genes
After data/293t_jurkat/jurkat_293t_50_50: 32643 genes
Found 32643 genes among all datasets
[[0.         0.00491099 0.705026  ]
 [0.         0.         0.29864948]
 [0.         0.         0.        ]]
Processing datasets data/293t_jurkat/293t <=> data/293t_jurkat/jurkat_293t_50_50
Processing datasets data/293t_jurkat/jurkat <=> data/293t_jurkat/jurkat_293t_50_50
[t-SNE] Computing 1801 nearest neighbors...
[t-SNE] Indexed 9531 samples in 0.406s...
[t-SNE] Computed neighbors for 9531 samples in 40.541s...
[t-SNE] Computed conditional probabilities for sample 1000 / 9531
[t-SNE] Computed conditional probabilities for sample 2000 / 9531
[t-SNE] Computed conditional probabilities for sample 3000 / 9531
[t-SNE] Computed conditional probabilities for sample 4000 / 9531
[t-SNE] Computed conditional probabilities for sample 5000 / 9531
[t-SNE] Computed conditional probabilities for sample 6000 / 9531
[t-SNE] Computed conditional probabilities for sample 7000 / 9531
[t-SNE] Computed conditional probabilities for sample 8000 / 9531
[t-SNE] Computed conditional probabilities for sample 9000 / 9531
[t-SNE] Computed conditional probabilities for sample 9531 / 9531
[t-SNE] Mean sigma: 0.091241
[t-SNE] Computed conditional probabilities in 10.583s
[t-SNE] Iteration 50: error = 54.4518127, gradient norm = 0.0203122 (50 iterations in 77.918s)
[t-SNE] Iteration 100: error = 49.3401184, gradient norm = 0.0016440 (50 iterations in 84.563s)
[t-SNE] Iteration 150: error = 49.1006927, gradient norm = 0.0007246 (50 iterations in 82.176s)
[t-SNE] Iteration 200: error = 49.0031929, gradient norm = 0.0004704 (50 iterations in 80.873s)
[t-SNE] Iteration 250: error = 48.9485016, gradient norm = 0.0003394 (50 iterations in 80.030s)
[t-SNE] KL divergence after 250 iterations with early exaggeration: 48.948502
[t-SNE] Iteration 300: error = 1.3712037, gradient norm = 0.0019137 (50 iterations in 80.450s)
[t-SNE] Iteration 350: error = 1.0990900, gradient norm = 0.0003722 (50 iterations in 81.477s)
[t-SNE] Iteration 400: error = 1.0313268, gradient norm = 0.0001744 (50 iterations in 81.692s)
[t-SNE] Error after 400 iterations: 1.031327
Error: mismatch, 9531 cells, 9530 labels
```

It still produces the `293t_jurkat_ds.svg` file, but no other outputs.

**Comment by robertamezquita** [comment]
Fix for the above issue with the mismatch is to add one more label to the `cell_labels/293t_jurkat_cluster.txt` file. After that fix, runs all the way through.

**Comment by robertamezquita** [comment]
Oh my goodness, I did not read the relevant section above the toy data set section...I needed to run process.py first!! Yikes. Sorry for the bother..

**Comment by brianhie** [comment]
@robertamezquita Ahh, glad to hear there was a resolution!

You can also write your own data set loading code (e.g., `scanpy.api.read`) and call Scanorama through the API -- having to call `bin/process.py` and loading through `.npz` files is just unique to these examples.

**Comment by robertamezquita** [comment]
One question though - is there a reason why the `load_mtx` version I used produces 9531 cells, versus the post-processed version (that generates the .npz files) having 9530 cells? I know it's a small difference, but just curious what might be causing this difference in total cells.

**Comment by brianhie** [comment]
@robertamezquita Oh, that is probably because `bin/process.py` applies a minimum unique genes filter (defined [here](https://github.com/brianhie/scanorama/blob/master/bin/process.py#L11)) and there is probably a single cell that's not meeting this filter, hence the discrepancy.

You can change the parameter by modifying `bin/process.py` or programmatically in the `process()` function, e.g.,
```
from process import process
process(data_names, min_trans=NEW_VALUE)
```

**Comment by robertamezquita** [comment]
Just wanted to make sure it wasn't something funky, thanks for being so responsive! Looking forward to the results!

**Comment by brianhie** [comment]
@robertamezquita Glad I could help!
