### ISSUE TITLE
inputs as parameters

### ISSUE THREAD

**Issue by igordot** [brianhie/scanorama#2]
This really isn't an issue, but more of a suggestion. Currently, the `data_names` variable for the input data must be hard-coded. Is it possible to make that a command-line argument? That way, you can just modify the command instead of having to edit a file every time you run scanorama.

**Comment by brianhie** [comment]
The interface could be modified to take in a path to a file with a list of data set names, e.g., a config.txt or something like that.  Passing in the entire list of names in the command line argument itself seems a bit unwieldy?

**Comment by igordot** [comment]
Either way would work. I personally think it's preferable to not have to deal with extra files since it's just a list of paths. Even in the very large example you used in your study, there were 26 datasets, which is fairly manageable as a string of arguments. It would also allow you to call the scanorama script with a single command from external tools without having an extra config-generation step.

If you prefer to store the arguments in a file, you could always treat it as a string with something like:
```
python bin/process.py <(cat datasets.txt)
```

Anyway, it's just a suggestion. I am glad you are at least entertaining the notion.

**Comment by brianhie** [comment]
@igordot I modified the interface to be able to read from either a config file or from standard input (as you suggested!).

So to do everything on the command line, you could do something like:
```
echo dataset1,dataset2 | python bin/process.py
```

Or just read it in from a config as the first argument to `bin/process.py` and `bin/panorama.py`.  Hope that'll be helpful!

**Comment by igordot** [comment]
Thanks for the quick resolution! I hope I am not the only one to find this helpful.
