### ISSUE TITLE
Minimal example with working R code 

### ISSUE THREAD

**Issue by robertamezquita** [brianhie/scanorama#21]
I am working in R using scanorama with the reticulate package, and tried running the integrate routine and got this error:

```
> integrated_data <- scanorama$integrate(scale_matrix_list, genes_list)
Found 4335 genes among all datasets
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  IndexError: index (4334) out of range

Detailed traceback: 
  File "/home/ramezqui/.local/lib/python3.7/site-packages/scanorama-0.4-py3.7.egg/scanorama/scanorama.py", line 147, in integrate
    ds_names=ds_names)
  File "/home/ramezqui/.local/lib/python3.7/site-packages/scanorama-0.4-py3.7.egg/scanorama/scanorama.py", line 282, in merge_datasets
    datasets[i] = datasets[i][:, uniq_idx]
  File "/home/ramezqui/.local/lib/python3.7/site-packages/scipy-1.1.0-py3.7-linux-x86_64.egg/scipy/sparse/csr.py", line 307, in __getitem__
    P = extractor(col,self.shape[1]).T        # [1:2,[1,2]]
  File "/home/ramezqui/.local/lib/python3.7/site-packages/scipy-1.1.0-py3.7-linux-x86_64.egg/scipy/sparse/csr.py", line 270, in extractor
    min_indx, max_indx = check_bounds(indices, N)
  File "/home/ramezqui/.local/lib/python3.7/site-packages/scipy-1.1.0-py3.7-linux-x86_64.egg/scipy/sparse/csr.py", line 256, in check_bounds
    raise IndexError('index (%d) out of range' % max_indx)
```

The matrices are contained in a list, each 4335 x [variable number of cells], and the genes are character vectors each of length 4335 and contained within a list. 

Is there a more detailed manual available with minimal working R examples? Maybe something is up on my end, not sure.

**Comment by brianhie** [comment]
The matrices should be cells x genes, this is one of the differences just in convention between Python and R. It definitely works for dense matrices but I haven’t tried sparse — maybe let me know if it works?

I’ll also clarify these in the README

**Comment by robertamezquita** [comment]
Wonderful! Yes, the issue was the matrix was not cells x genes. 

Another small thing when creating the reproducible R `reticulate` example:

```
integrated_data <- scanorama$integrate(matrix_ll$alra, genes_list, return_dense = TRUE)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: integrate() got an unexpected keyword argument 'return_dense'
```

Sorry to be bugging you so much, thank you for your help!

**Comment by brianhie** [comment]
@robertamezquita Oops, `integrate()` always returns dense matrices so it doesn't have a `return_dense` parameter. I've updated the README to be clear about the matrix dimensions and removed the `return_dense` parameter from the R example. Thank you for testing things out and catching my mistakes!
