### ISSUE TITLE
Workflow Question

### ISSUE THREAD

**Issue by robertamezquita** [brianhie/scanorama#22]
Hi Brian,

I read over the manuscript, and wanted to ask if you could explain some finer details of your preprocessing workflow. I got some preliminary results from scanorama, but unfortunately some of my cell populations got mixed in with each other that should definitely be discrete. Thank you in advance!

In your README you say that scanorama is downstream of other preprocessing steps (and manuscript has filtering out low quality cells, l2 normalization). Did you also reduce the matrices to be only genes that are highly variable? Should technical effects (or any other covariates) such as the number of UMIs be regressed out before feeding the data into scanorama? 

Also, once the scanorama corrected matrices are returned, do you think imputation on this matrix would be appropriate? Additionally, setting dimred = TRUE returns a lower dimensional representation of the data. Is this the SVD calculation results, and would this be appropriate to then input into a tSNE/UMAP calculation?

Thanks for your time and any other tips you might have to offer to get the data to behave nicely!

**Comment by brianhie** [comment]
@robertamezquita yes I'd do whatever preprocessing steps you are doing on each data set individually (highly variable gene filtering and filtering out low quality cells I've found particularly helpful). Imputation would probably work best by being applied to each individual data set first, though I have not tried this extensively. The low dimensional representation should be what you input into t-SNE or UMAP. I might also try turning the smoothing down by setting the `sigma` parameter to something smaller (around 20-50). If your total number of cells is on the smaller size and you are noticing overcorrection, you could try setting the `knn` parameter lower (to maybe 5 or 10).
