### ISSUE TITLE
Use all genes or highly variable genes for scanorama?

### ISSUE THREAD

**Issue by ahy1221** [brianhie/scanorama#23]
Hi Brian,
I am trying integrated 4 SC datasets across different platfrom (10X , dropseq and inDrop) . 
As mnnCorrect() in scran recommend to use HVGs as input, I didn't see any discussion about feature selection.
I want to asked that should I use all genes (after filtering low abundance genes) or just HVGs in each dataset for scanorama.correct() ?

Any advice would be appreciated !

**Comment by brianhie** [comment]
@ahy1221 Scanorama should be used downstream of HVG filtering and other noise reduction methods, and I'd recommend doing the HVG filtering from something like scran especially if you find it helps reduce noise in your original data sets.  Scanorama's `correct()` function can essentially be thought of as a replacement for the `mnnCorrect()` functionality in scran.

**Comment by zhumengyan** [comment]
Hi Brain,
Sorry to reopen the issue. I have a questions. I don't know "HVG filtering" means remove HVG or only use HVG in the dataset?
Mengyan Zhu

**Comment by brianhie** [comment]
Hi @zhumengyan,

Some RNA-seq pipelines filter out lowly variable genes, i.e., keep only the most highly variable genes. For example, see the "Feature selection" section of this review: https://www.embopress.org/doi/full/10.15252/msb.20188746 or this benchmark paper: https://academic.oup.com/bib/advance-article/doi/10.1093/bib/bby011/4898116

**Comment by davisidarta** [comment]
Hi @brianhie 

How can I run scanorama using all genes? Selecting only HVG filters out some genes of interest, and makes it impossible to imputate the data after merging.

**Comment by brianhie** [comment]
Hi @davisidarta,

Scanorama doesn't use highly variable genes by default. It does, by default, take the intersection of genes across the datasets you are merging. So if a particular gene is absent in one of your datasets, it will be excluded.

You can easily switch to taking the union of genes by passing the `union=True` flag to either `correct()` or `integrate()`.
