### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by DarioS** [brianhie/scanorama#26]
[What she said](https://www.bioverlay.org/post/2018-09-scrnaseq-data-integration-scanorama/).

> 6. The authors should consider submitting the software to something like PyPi so that users will be able to install via `pip` to make Scanorama more accessible to the scientific community.

The easier it is to install Scanorama on research servers at university, the better.

**Comment by brianhie** [comment]
@DarioS Noted! Currently very busy and will look into doing this very soon. Right now you can just clone into the repo and do
```
pip install .
```
I'll upload to PyPi once I get a little more time.

**Comment by brianhie** [comment]
@DarioS apparently doing this was easier than I thought... Can you try doing
```
pip install scanorama
```
and see if that works?

**Comment by DarioS** [comment]
`pip install .` of the contents from GitHub almost works. The server runs Debian 9.

```
$ python bin/293t_jurkat.py
ImportError: libpng12.so.0: cannot open shared object file: No such file or directory
```

I read that this library was available for Debian 8, but is no longer in the repositories.

**Comment by brianhie** [comment]
@DarioS that's unfortunate, I hope you can find a reasonable workaround.

I'm going to close this issue since it appears not to be related to Scanorama, but feel free to reopen if you get matplotlib working and still run into installation issues.
