### ISSUE TITLE
Cross species comparison

### ISSUE THREAD

**Issue by s18692001** [brianhie/scanorama#32]
Hi there,

I have single cell data from 3 different species. I'm curious that is Scanorama a proper tool for different species comparison?

**Comment by s18692001** [comment]
Also, after I use Scanorama across different species and plot in tSNE or UMAP, they seem to be separated significantly. Is there any way that I can tune them by parameters?

**Comment by s18692001** [comment]
Hi @brianhie, thanks for your fast reply. Could you explain more about "call cell types within each species individually, before integration."? What function should I use for this purpose? Thanks!

**Comment by s18692001** [comment]
> Hi @s18692001,
> 
> I've had some success with cross-species integration before. And yes, increasing the knn value will also increase the strength of the alignment to a certain extent, but if the cross-species variation is substantial it will only work so well.
> 
> One way to tune knn might be to call cell types within each species individually, before integration. Then, integrate using Scanorama and see how well those cell types integrate, and if there is any overcorrection (for example, completely different cell types aligning). Typically Scanorama has a much harder time overcorrecting than undercorrecting, but you could gauge this especially if you have confident cell type labels.

Hi @brianhie, thanks for your fast reply. Could you explain more about "call cell types within each species individually, before integration."? What function should I use for this purpose? Thanks!

**Comment by brianhie** [comment]
@s18692001 how are you analyzing the datasets prior to integration? Typical scRNA-seq workflows might perform an unsupervised clustering analysis of the dataset, where those clusters correspond to "cell types." E.g., https://scanpy.readthedocs.io/en/stable/tutorials.html#clustering
