### ISSUE TITLE
Incorrect order of return value for correct_scanpy in dosctring

### ISSUE THREAD

**Issue by arkal** [brianhie/scanorama#34]
https://github.com/brianhie/scanorama/blob/d995504f840bce855e138a985953569379d7502f/scanorama/scanorama.py#L189

Order should be `integrated, corrected`

Also, shouldn't this case be when `return_dimred=True`?

**Comment by brianhie** [comment]
@arkal great catch! Updated documentation in https://github.com/brianhie/scanorama/pull/35 Thank you!
