### ISSUE TITLE
The number of downloaded 10x Jurkat cells does not match with the paper

### ISSUE THREAD

**Issue by genecell** [brianhie/scanorama#36]
Hi,

I downloaded the dataset from[http://cb.csail.mit.edu/cb/scanorama/](url) and analyzed the 293T:Jurkat dataset, but I found the number of Jukrat cells in the original 10x dataset (pure 100%, n=3258 cells) does not match with the reported number (n=3257 cells) in your NBT paper. In addition, the number of Jurkat cells (pure 100%) is 3257 in the assigned cell labels file: **"data/cell_labels/293t_jurkat_cluster.txt"**.
Could you please offer me some instructions to adjust the Jurkat cell number, thanks in advance!

Best regards,
BP

**Comment by brianhie** [comment]
Hi @genecell, did you try filtering for at least 600 unique genes?

**Comment by genecell** [comment]
Hi @brianhie, thank you for your rapid reply, I didn't perform cell QC, and will do it right away.

**Comment by brianhie** [comment]
@genecell sure, the analysis is doing something like this https://github.com/brianhie/scanorama/blob/master/bin/process.py#L101

Will close but do feel free to reopen if you still notice a discrepancy

**Comment by genecell** [comment]
Thank you @brianhie, it works for me now!

Best regards,
BP
