### ISSUE TITLE
Could not find: data/macrophage/monocytes

### ISSUE THREAD

**Issue by genecell** [brianhie/scanorama#37]
Hi,

I was running the **monocyte_macrophage.py**, and met this error:
```
Warning: Could not find data/macrophage/monocytes
Successfully processed data/pbmc/10x/cd14_monocytes
Successfully processed data/macrophage/mcsf_day3_1
Successfully processed data/macrophage/mcsf_day3_2
Successfully processed data/macrophage/mcsf_day6_1
Successfully processed data/macrophage/mcsf_day6_2
Could not find: data/macrophage/monocytes
```
The data I downloaded in the **data/macrophage** directory are:
```
infected.txt     mcsf_day6_2.npz     mono_macro_diffexpr.txt
mcsf_day3_1.npz  mcsf_day6_2.txt     mono_macro_genes.txt
mcsf_day3_1.txt  mixed_infected.txt  mono_macro_hours.txt
mcsf_day3_2.npz  monocytes_1.txt     mono_macro.txt
mcsf_day3_2.txt  monocytes_2.txt     uninfected_donor2.txt
mcsf_day6_1.npz  monocytes_3.txt     uninfected.txt
mcsf_day6_1.txt  monocytes_4.txt
```
Could you please give me some advices on how to integrate monocytes_(1,2,3,4).txt to monocytes.txt, or should I add these four monocytes_(1,2,3,4).txt files as extra input for integration?

Thanks in advance,
BP

**Comment by brianhie** [comment]
Hi @genecell, I just checked the data available for download and the monocytes.txt is there. Can you try downloading the most recent version?

**Comment by genecell** [comment]
Hi @brianhie, no problem, the data showed above should be downloaded last year. I will check the latest version of the dataset right away. Thank you!

**Comment by brianhie** [comment]
@genecell great!
