### ISSUE TITLE
Question about the values returned by scanorama.correct() with and without return_dimred

### ISSUE THREAD

**Issue by friedue** [brianhie/scanorama#39]
Hi Bryan,

thanks for the great tool! I've tried out the example code you gave for using `scanorama` via `reticulate` and I just have a question regarding the output returned by `scanorama.correct`.
In your example code, you run that function twice, once with `return_dimred` turned on and once turned off. I assumed, the only difference was going to be that one will result in a bigger object than the other but that the corrected values should be the same. This is not 100% the case when I look at my data though and I was wondering where the differences are coming from.

```
integrated.corrected.data <- scanorama$correct(datasets, genes_list,
                                               return_dimred=TRUE, 
                                               return_dense=TRUE)
                                               
corrected.data <- scanorama$correct(datasets, genes_list, 
                                    return_dense=TRUE)
                                    
 > str(corrected.data)
List of 2
 $ :List of 3
  ..$ : num [1:4337, 1:17281] 2.20e-04 1.92e-05 1.77e-05 1.64e-05 1.66e-05 ...
  ..$ : num [1:5839, 1:17281] 2.71e-04 6.28e-05 4.65e-05 6.58e-05 5.86e-05 ...
  ..$ : num [1:2835, 1:17281] 3.36e-05 3.58e-05 4.41e-05 5.40e-05 3.28e-04 ...
 $ : chr [1:17281(1d)] "ENSMUSG00000000001" "ENSMUSG00000000028" "ENSMUSG00000000031" "ENSMUSG00000000037" ...
 
 
 > str(integrated.corrected.data)
List of 3
 $ :List of 3
  ..$ : num [1:4337, 1:100] -0.0513 -0.0731 -0.0565 -0.107 -0.2204 ...
  ..$ : num [1:5839, 1:100] 0.2674 0.2699 -0.0853 0.2077 0.1268 ...
  ..$ : num [1:2835, 1:100] -0.0854 -0.1937 -0.4252 -0.4026 -0.2517 ...
 $ :List of 3
  ..$ : num [1:4337, 1:17281] 2.22e-04 2.13e-05 1.97e-05 1.86e-05 1.95e-05 ...
  ..$ : num [1:5839, 1:17281] 2.71e-04 6.26e-05 4.81e-05 6.52e-05 5.90e-05 ...
  ..$ : num [1:2835, 1:17281] 3.54e-05 3.83e-05 4.84e-05 6.08e-05 3.31e-04 ...
 $ : chr [1:17281(1d)] "ENSMUSG00000000001" "ENSMUSG00000000028" "ENSMUSG00000000031" "ENSMUSG00000000037" ...
```

I was under the impression that the content of the second list of `integrated.corrected.data` should be the same as the first list of `corrected.data`, but that doesn't seem to be the case. Can you explain to me what I'm missing? Thanks a lot!

**Comment by brianhie** [comment]
Hi @friedue,

What a tricky issue but I think I've found out why this was happening. The first call to `scanorama$correct` was mutating the values within `datasets` (filtering out genes not in the intersection), causing the values to be different on the second call to `correct()`.

If you only make one call to `correct()` (e.g., by running the script separately for each call) then it should return the same result. I'm also fixed this strange behavior in https://github.com/brianhie/scanorama/pull/40

**Comment by brianhie** [comment]
Oops, it wasn't due to that, sorry! There's a lot of (pseudo-)randomness in the underlying algorithm and that was causing the discrepancy. If you fix the random seed before each call to `correct()`, as I have done here (https://github.com/brianhie/scanorama/pull/41), then you get the same output. I also changed the parameters so you can specify different seeds

**Comment by brianhie** [comment]
If you reinstall version 1.2 (https://github.com/brianhie/scanorama/releases/tag/v1.2), they should give the same output!

**Comment by friedue** [comment]
Thanks for the swift reply!
I thought it was randomness causing it, but I re-ran all the lines a couple of times and always got the same values (with their differences), which is why assumed it was something else.
Since I'm using it via R and reticulate, do you know what the best way to set the seed would be?

**Comment by brianhie** [comment]
If you upgrade to the latest version (pip install scanorama --upgrade), you should be able to pass the same seed into both calls of correct (I.e., correct(data, ..., seed=0).

**Comment by friedue** [comment]
I see! Thanks!

I can confirm that

1. the default now works fine and generates the same numbers;
2. setting the seed via `reticulate` and `seed=4L` works fine (it must have the "L", though, just as a note for future readers)

**Comment by brianhie** [comment]
Glad you confirmed that this is consistent.
