### ISSUE TITLE
Integration vs Preprocessing

### ISSUE THREAD

**Issue by ilyakorsunsky** [brianhie/scanorama#4]
Very excited to try this method on my data! I have a design question that is not clear to me. Which methods can be replaced by any pre-processing pipeline and which are core methods for integration? For instance, if I process raw data through PCA in Seurat or Scanpy, can I run the assemble method on the PC matrices and expect similar results? It would be helpful to have this distinction reflected in the code base.

**Comment by brianhie** [comment]
Great question, as long as your preprocessing steps approximately preserve the relative distances between points, you can run the `assemble()` method on those data sets. Preprocessing with PCA, in your example, will be fine.

So assuming you have data preprocessed (hopefully in a way that reduces the dimension of the data) through Seurat or Scanpy and stored in a `datasets` variable (a list of numpy matrices), you can run the integration with the command:
```
datasets_integrated = assemble(datasets)
```
`datasets_integrated` will also be a list of numpy matrices, but where the values have also been transformed to bring together matched cells.

There are also [optional parameters](https://github.com/brianhie/scanorama/blob/master/bin/scanorama.py#L385) for the `assemble()` method that are configurable as well.

I guess you can think of the `correct()` method as doing integration _and batch correction_ of the full gene expression values, while the `assemble()` method just does integration.

**Comment by ilyakorsunsky** [comment]
Thanks, that's very helpful!
