### ISSUE TITLE
Integration different seq data

### ISSUE THREAD

**Issue by s18692001** [brianhie/scanorama#42]
Is it possible to use Scanorama to integrate both single cell DNA methylation and single cell RNA-seq data by Scanorama, and then use RNA-seq data to identify the cell types that clustered with methylation dataset?

Thanks!

**Comment by brianhie** [comment]
@s18692001 How is the methylation data featurized? Is it in a cell-by-gene matrix? If so, it's worth giving it a shot, but I haven't tried using Scanorama for multimodal integration.

**Comment by s18692001** [comment]
Yes, it's a cell-by-gene matrix
