### ISSUE TITLE
Could not find function "add.Gaussian.noise" in simulate_nonoverlap.R

### ISSUE THREAD

**Issue by genecell** [brianhie/scanorama#43]
Hi,

I was running the **_scanorama/bin/R/simulate_nonoverlap.R_**, and met this error:
```
[Show in New Window] [Clear Output] [Expand/Collapse Output]
Error in add.Gaussian.noise(counts(sim.groups.A)) : could not find function "add.Gaussian.noise"
```
Is this function implemented elsewhere or is it imported from other packages?
I found the function elsewhere: [https://www.rdocumentation.org/packages/RMThreshold/versions/1.1/topics/add.Gaussian.noise](), but not sure I should use it or not.

By the way, I found the following codes a little bit strange, since **sim.groups.A** has already been output to files and therefore needs no more operations. Should I replace **sim.groups.A** with **sim.groups.B** here?
```
sim.groups.B <- splatSimulate(
    batchCells = c(1000), group.prob = c(0, 0, 0.50, 0.50),
    method = "groups", verbose = FALSE
)
sim.groups.A <- splatSimBatchEffects(sim.groups.A, newSplatParams())
```
Thanks in advance,
BP

**Comment by brianhie** [comment]
That's probably the right function and those variables should probably be replaced

**Comment by genecell** [comment]
Hi @brianhie,

Okay, thanks for your rapid reply.
The **add.Gaussian.noise** function cannot be directly applied to the counts data, since it will lead to some values to be negative. Can I choose to skip this **add.Gaussian.noise** step here in the simulation process? Thank you!

Best regards,
BP

**Comment by brianhie** [comment]
Sure, although I think simulations can only go so far and it's best to look at real data. There may be alternative simulations you could run as well.

**Comment by genecell** [comment]
Yes, you are right. Thanks!
