### ISSUE TITLE
Insights about corrected expression values

### ISSUE THREAD

**Issue by friedue** [brianhie/scanorama#44]
Hi Brian,

I was wondering whether you could explain the interpretation and downstream usage of the batch-corrected expression values returned by scanorama a bit more. I understand that you're adding weights based on a translation vector to the individual values, but I'm not sure I totally understand the nature of the returned values and how to use them for typical differential gene expression analyses. 

I noticed that the range of the values seems to be capped at 1, but the lower limit is somewhat elusive.

```
> lapply(integrated.corrected.data[[2]], min)
[[1]]
[1] -0.0006699665

[[2]]
[1] -0.006567805

[[3]]
[1] -0.01890116
```

Did you test them with any of the "gene marker" finding tools, e.g. Seurat's or scater's findMarkers, which basically use wrappers around the tools developed for bulk RNA-seq, that will often turn to the integer count values? Do you have any comments on that?

**Comment by brianhie** [comment]
The values do not really have any absolute meaning, only relative meaning within the panorama, and there may be negative values as well, for similar reasons as described in this thread: https://github.com/MarioniLab/scran/issues/5. So, you could compare genes between cells _within_ a panorama, but the value itself isn't comparable to values _outside_ the panorama. So differential expression that tests for relative differences in distributions can be done on those values, as long as the analysis is "contained" within a single Scanorama-corrected dataset collection.

This is actually (what I think is) a big open problem with integrative methods for scRNA-seq integration -- methods that modify gene expression values (even those that enforce nonnegativity) only have relative interpretability and not absolute interpretability.

**Comment by friedue** [comment]
Thanks, Brian, the MarioniLab thread was very informative. However, Aaron Lun explicitly states that he would not use the MNN-corrected values for DE analyses, even within the same batch corrected set -- you seem to say that you think this should be ok.

Typically, DE analysis is used to identify markers of subpopulations within a larger context, i.e., I actually don't think that many researchers are currently looking for DE detection methods across strictly separate data sets -- and, after all, is there any reason *not* to generate one big panorama out of the universe of all cells one would be possibly interested in?

**Comment by brianhie** [comment]
That's weird that he says that because they actually do DE on corrected values in their paper. But sure, the gene expression values should be treated with caution and working to get more interpretable integration is and important and unsolved direction.
