### ISSUE TITLE
'Error after 400 iterations' message

### ISSUE THREAD

**Issue by xiebb123456** [brianhie/scanorama#52]
Hi,

I'm running the 293t data on my machine, follow the tutorial comand, when running python bin/293t_jurkat.py the last output message 'Error after 400 iterations: 1.044037', it still generate the svg figure, I don't know whether it is just running message or have something wrong in it, just want to make sure the result is right.

python bin/process.py conf/panorama.txt

Successfully processed data/293t_jurkat/293t
Successfully processed data/293t_jurkat/jurkat
Successfully processed data/293t_jurkat/jurkat_293t_50_50

python bin/293t_jurkat.py

Loaded data/293t_jurkat/293t with 32738 genes and 2885 cells
Loaded data/293t_jurkat/jurkat with 32738 genes and 3257 cells
Loaded data/293t_jurkat/jurkat_293t_50_50 with 32738 genes and 3388 cells
Found 9530 cells among all datasets
After data/293t_jurkat/293t: 32639 genes
After data/293t_jurkat/jurkat: 32639 genes
After data/293t_jurkat/jurkat_293t_50_50: 32639 genes
Found 32639 genes among all datasets
[[0.         0.00859687 0.71265165]
 [0.         0.         0.26251151]
 [0.         0.         0.        ]]
Processing datasets data/293t_jurkat/293t <=> data/293t_jurkat/jurkat_293t_50_50
Processing datasets data/293t_jurkat/jurkat <=> data/293t_jurkat/jurkat_293t_50_50
[t-SNE] Computing 1801 nearest neighbors...
[t-SNE] Indexed 9530 samples in 0.320s...
[t-SNE] Computed neighbors for 9530 samples in 33.926s...
[t-SNE] Computed conditional probabilities for sample 1000 / 9530
[t-SNE] Computed conditional probabilities for sample 2000 / 9530
[t-SNE] Computed conditional probabilities for sample 3000 / 9530
[t-SNE] Computed conditional probabilities for sample 4000 / 9530
[t-SNE] Computed conditional probabilities for sample 5000 / 9530
[t-SNE] Computed conditional probabilities for sample 6000 / 9530
[t-SNE] Computed conditional probabilities for sample 7000 / 9530
[t-SNE] Computed conditional probabilities for sample 8000 / 9530
[t-SNE] Computed conditional probabilities for sample 9000 / 9530
[t-SNE] Computed conditional probabilities for sample 9530 / 9530
[t-SNE] Mean sigma: 0.094365
[t-SNE] Computed conditional probabilities in 8.172s
[t-SNE] Iteration 50: error = 53.7817993, gradient norm = 0.0253594 (50 iterations in 62.223s)
[t-SNE] Iteration 100: error = 49.3612633, gradient norm = 0.0013276 (50 iterations in 66.378s)
[t-SNE] Iteration 150: error = 49.1272125, gradient norm = 0.0007659 (50 iterations in 65.474s)
[t-SNE] Iteration 200: error = 49.0316925, gradient norm = 0.0004471 (50 iterations in 64.936s)
[t-SNE] Iteration 250: error = 48.9777985, gradient norm = 0.0003479 (50 iterations in 63.844s)
[t-SNE] KL divergence after 250 iterations with early exaggeration: 48.977798
[t-SNE] Iteration 300: error = 1.3533084, gradient norm = 0.0019510 (50 iterations in 64.437s)
[t-SNE] Iteration 350: error = 1.1094712, gradient norm = 0.0003535 (50 iterations in 64.903s)
[t-SNE] Iteration 400: error = 1.0440365, gradient norm = 0.0001733 (50 iterations in 65.079s)
**[t-SNE] Error after 400 iterations: 1.044037**

Loaded data/293t_jurkat/293t with 32738 genes and 2885 cells
...

**Comment by brianhie** [comment]
Hi @xiebb123456,

That's a slightly misleading message -- that refers to the the KL divergence loss or "error" function and not to a Python runtime error or anything like that.

Looks like the job completed successfully!

**Comment by xiebb123456** [comment]
Thank you!
