### ISSUE TITLE
Reversing L2-normalisation in corrected data

### ISSUE THREAD

**Issue by dblux** [brianhie/scanorama#53]
Hi Brian, thanks for the good work on scanorama! It is mentioned in your paper that expression values are L2-normalised before batch correction. I presume that this is the reason why the corrected values are much smaller than the input values. Is there an option in the correct function that would allow us to reverse the L2-normalisation? Thank you

**Comment by brianhie** [comment]
@dblux looks like there's currently no option in the API to perform scanorama without L2 normalization. I could add a flag that disables it, but that would be out of the realm of what we tried and an unrecommended choice. Why are you interested in performing integration without L2 normalization?

**Comment by dblux** [comment]
@brianhie the MNN function does provide an option not to perform L2-normalisation (i.e. cosine normalisation) before correcting the values, but still perform L2-normalisation for the data before the calculation of distances in the kNN search. I was wondering whether there was a similar function in Scanorama in order not to get scaled values that are very small (e.g. mean of magnitude 10-3) as compared to the values (e.g. mean of 5) before. I understand that it is recommended to perform L2-normalisation to make comparison scale-invariant, just thought that adding the option would allow users to perform their own preferred method of normalisation beforehand.

**Comment by brianhie** [comment]
Won't work on this now, but would be happy to review a pull request implementing different normalizations.
