### ISSUE TITLE
how to set reduced dimension

### ISSUE THREAD

**Issue by screamer** [brianhie/scanorama#56]
I used the following code to get the integrated and corrected data.

datasets=[adata_b1,adata_b2]
integrated, corrected = scanorama.correct_scanpy(datasets, return_dimred=True)

Is there a way to set the number of reduced dimension?

**Comment by brianhie** [comment]
You can set the dimension with the `dimred` parameter: https://github.com/brianhie/scanorama/blob/master/scanorama/scanorama.py#L57
