### ISSUE TITLE
Matplotlib backend settings prevent plot display in jupyter notebook

### ISSUE THREAD

**Issue by giovp** [brianhie/scanorama#58]
Importing scanorama setts the `agg` backend which prevents plots to be visualized in jupyter notebook.

```python
sc.pl.umap(adata, color = ["clusters"])
>>> /Users/giovanni.palla/Projects/scanpy/scanpy/plotting/_utils.py:307: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  pl.show()
```

Is this line needed?
https://github.com/brianhie/scanorama/blob/a437be57e6bad27001d502c516205e2f8c9237c7/scanorama/utils.py#L5

Setting back to standard jupyter inline backend works:
`mpl.use('module://ipykernel.pylab.backend_inline')`

Session info:
```
seaborn==0.9.0
scanorama==1.5
pandas==0.25.3
numpy==1.18.1
matplotlib==3.1.1
scanpy==1.4.5.post3.dev27+gcea5f4f.d20200212
anndata==0.7.2.dev13+g4440b90
```

**Comment by brianhie** [comment]
I agree! Should not be setting matplotlib defaults in package import, removed in https://github.com/brianhie/scanorama/pull/59
