### ISSUE TITLE
_binary_search_perplexity takes exactly 3 positional arguments (4 given)

### ISSUE THREAD

**Issue by Puriney** [brianhie/scanorama#63]
Hello I tried to use the tSNE visualization in the package. However, I met across this error:

> TypeError: _binary_search_perplexity() takes exactly 3 positional arguments (4 given)

https://github.com/brianhie/scanorama/blob/fdd1232c0fb96b0a3ddeaeabd0cb69e0b979a104/scanorama/t_sne_approx.py#L63-L64

I realized the sklearn's _binary_search_perplexity function changed their parameters design from 4 to 3 parameters.

From [this](https://github.com/scikit-learn/scikit-learn/blame/e5be3ad025fe372f4811a2c5ffb5b6fb5bfcc8f1/sklearn/manifold/_utils.pyx#L15-L30) (currently assumed by Scanorama) to [this](https://github.com/scikit-learn/scikit-learn/blame/c71a1c21d14fc7a98493acb1f3d315db720ca4ac/sklearn/manifold/_utils.pyx#L19-L22) (currently in the latest sklearn).

If there any way to make Scanorama work? Thank you.

Both sklearn 0.22.2 and 0.22.1 have this problem.

**Comment by Puriney** [comment]
I don't know if it makes sense to simply remove the second parameters as called in Scanorama.

**Comment by brianhie** [comment]
@Puriney it's probably better to use a t-SNE other than the custom one, which would be faster and better supported. I've removed the custom t-SNE modifications in https://github.com/brianhie/scanorama/pull/64 and the code in Scanorama can still use https://github.com/DmitryUlyanov/Multicore-TSNE. There's also ways to visualize, like in the scanpy package.
