### ISSUE TITLE
Does scanorama require scaled data or not?

### ISSUE THREAD

**Issue by salwanbutrus** [brianhie/scanorama#68]
Thank you so much for this great tool! I have a simple question. After finding highly variable genes, should the data be scaled prior to implementing scanorama or not?

**Comment by brianhie** [comment]
@salwanbutrus sorry for the late reply! I'd recommend normalization, log transformation, then (optionally) HVGs, then directly input into Scanorama as done here: https://www.biorxiv.org/content/10.1101/2020.05.22.111161v1.full
