### ISSUE TITLE
Recover Gene/Feature Loadings from the computed PCA (SC) for downstream analysis?

### ISSUE THREAD

**Issue by Mochikris** [brianhie/scanorama#75]
Hi,
Thanks for developing Scanorama. Despite having little coding experience in R and Python, its use has been relatively easy, resulting in a great integration of my dataset.
I am now wondering if it would be possible to get the gene/feature loadings for the computed scanorama PCAs, as these are required for other downstream analysis (i.e. finding gene modules in Monocle 3).

I am sorry if this is a silly question, I am posting it as I couldn't find an answer to it.

Many thanks in advance.

**Comment by brianhie** [comment]
Great to hear you've found it easy to use! While the Scanorama API doesn't expose the feature loadings, it's easy to recompute them. Under the hood, Scanorama just [concatenates](https://github.com/brianhie/scanorama/blob/ffc17a3e6f7f88185d3626e1f47a5a63348dff01/scanorama/scanorama.py#L371) the datasets to integrate, and then computes the [SVD of the concatenated matrix](https://github.com/brianhie/scanorama/blob/ffc17a3e6f7f88185d3626e1f47a5a63348dff01/scanorama/utils.py#L25). Scanorama doesn't produce an "integrated" equivalent of the gene loadings, and I'm not sure if this is what downstream modules expect, but you could also try using the feature loadings of the individual batches if you are really concerned about potential batch effects. Hope that is somewhat helpful!
