### ISSUE TITLE
Unable to get results

### ISSUE THREAD

**Issue by Zhaohui-Ruan** [brianhie/scanorama#83]
When I use Scanorama, sometimes the program gets stuck at this step and does not produce results for a long time. Can you help me solve this problem? Thank you very much！
![image](https://user-images.githubusercontent.com/70806190/114125967-15e5f400-992a-11eb-8143-ad5068ceeda9.png)

**Comment by brianhie** [comment]
Hi @Zhaohui-Ruan,

Looks like Scanorama is still running, but it may take longer on a large dataset. Can you try the `integrate()` function? That should be sufficient for most tasks.

**Comment by Zhaohui-Ruan** [comment]
Hi brianhie,

Thank you for your answer, I have solved this problem. : )
Ruan
