### ISSUE TITLE
about batch correction in CTRL and STIM

### ISSUE THREAD

**Issue by tanasa** [brianhie/scanorama#84]
Dear all,

i would appreciate your opinions, comments, advises on the following please :

<> we do have a two batches of scRNA-seq in CTRL (batch 1 and batch2), and two batches of scRNA-seq in STIM conditions (batch1 and batch2) (the batches were generated at an interval of 1-2 months between each other);

<> we had to integrate/combine those two batches of CTRL, and those two batches of STIM, in order to have a sufficient number of cells in each cluster, and to call conserved and differential markers;

if i may ask for your confirmation, please, the question would be : when we do batch correction with Scanorama, or other algorithms, would these algorithms correct also the fact that the two batches of CTRL and the two batches of STIM were produced at different time points and integrated in a CTRL matrix and in a STIM matrix ?

thanks a lot,

-- bogdan

**Comment by brianhie** [comment]
Hi @tanasa, ideally the integration tool would identify the similar cell types across all four batches, and I might expect the cells in the two "CTRL" conditions to be more similar to each other to the cells in the "STIM" conditions if an integration tool is able to remove batch effect while preserving biological difference.

**Comment by tanasa** [comment]
Dear Brian, thank you very much for your prompt reply !
