### ISSUE TITLE
The integrated showing error

### ISSUE THREAD

**Issue by honghh2018** [brianhie/scanorama#93]
Hi guy,
 When i runing on below step,
adatas_cor = scanorama.correct_scanpy(adatas, return_dimred=True) 
 It was complain about error:
Error: No genes found in all datasets, exiting...
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_146881/3261772617.py in <module>
----> 1 adatas_cor = scanorama.correct_scanpy(adatas, return_dimred=True)

/share/nas1/Data/software/mini_conda/Miniconda3/envs/Scanpy_package/lib/python3.8/site-packages/scanorama/scanorama.py in correct_scanpy(adatas, **kwargs)
    219     """
    220     if 'return_dimred' in kwargs and kwargs['return_dimred']:
--> 221         datasets_dimred, datasets, genes = correct(
    222             [adata.X for adata in adatas],
    223             [adata.var_names.values for adata in adatas],

/share/nas1/Data/software/mini_conda/Miniconda3/envs/Scanpy_package/lib/python3.8/site-packages/scanorama/scanorama.py in correct(datasets_full, genes_list, return_dimred, batch_size, verbose, ds_names, dimred, approx, sigma, alpha, knn, return_dense, hvg, union, seed)
     90     datasets_full = check_datasets(datasets_full)
     91 
---> 92     datasets, genes = merge_datasets(datasets_full, genes_list,
     93                                      ds_names=ds_names, union=union)
     94     datasets_dimred, genes = process_data(datasets, genes, hvg=hvg,

/share/nas1/Data/software/mini_conda/Miniconda3/envs/Scanpy_package/lib/python3.8/site-packages/scanorama/scanorama.py in merge_datasets(datasets, genes, ds_names, verbose, union)
    336         if len(keep_genes) == 0:
    337             print('Error: No genes found in all datasets, exiting...')
--> 338             exit(1)
    339     if verbose:
    340         print('Found {} genes among all datasets'

NameError: name 'exit' is not defined

So how can i fix this issue?
Any advice would be appreciated

**Comment by brianhie** [comment]
Hi @honghh2018, could you make sure that the genes you are passing to scanorama are the same? By default, it will take the intersection of all gene sets.
